#!/usr/bin/env sh

TMP_DIR=/tmp/ffmpeg_cut_merge
PARTS_FILE=/tmp/ffmpeg_cut_merge/parts

timestamps=$1
video=$2

# check if files exist; if not exit
[ ! -e $timestamps ] || [ "$timestamps" = "" ] &&\
  echo "ERROR: Timestamps file not found" && exit 1
[ ! -e $video ] || [ "$video" = "" ] &&\
  echo "ERROR: Video file not found" && exit 1
[ "$(file $timestamps | awk '{print $2}')" != "ASCII" ] &&\
  echo "Timestamps file not valid" && exit 1
mkdir $TMP_DIR

i=0
for line in $(cat $timestamps); do
  start_timestamp=$(echo $line | cut -d '-' -f 1)
  stop_timestamp=$(echo $line | cut -d '-' -f 2)
  part="$TMP_DIR/part-$i.mkv"
  ffmpeg -loglevel quiet -ss $start_timestamp -to $stop_timestamp\
    -i $video -c copy $part
  [ $? != 0 ] && echo "ERROR: could not cut video file" && break
  echo "file '$part'" >> $PARTS_FILE
  i=$(echo "$i+1" | bc)
done

ffmpeg -loglevel quiet -f concat -safe 0\
  -i $PARTS_FILE -c copy $(basename $video | cut -d '.' -f 1)_cut.mkv
rm -rf $TMP_DIR
rm $timestamps
